cache:
  paths:
    - node_modules
stages:
  - build
  - docker-build
build:
  image: node:latest    
  stage: build
  variables: 
    # Replace this with your site URL
    # PUBLIC_URL: http://124.221.67.248:8929/hope-front-end/  
  script:
    - yarn config set registry https://registry.npmmirror.com/
    - yarn install      
    - yarn build
  artifacts:
    paths:
      - build       
      - node_modules/
docker-build:
  stage: docker-build
  image: docker:latest
  services: 
    - name: docker:19.03.8-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"