cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
stages:
  - build
  - docker-build
  - deploy
build:
  stage: build
  image: node:16.15.0    
  script:
    - yarn config set registry https://registry.npmmirror.com/
    - yarn install      
    - yarn build
  artifacts:
    name: hope-build
    paths:
      - build
      - node_modules/    
docker-build:
  stage: docker-build
  image: docker:latest
  services: 
    - name: docker:19.03.8-dind
  before_script:
    - docker login -u lourd -p zyd1362848650 http://124.221.67.248:5005
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"