version: '2'
services:
  nginx-react:
    container_name: ngixreactapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:443
    environment:
      NODE_ENV: production
